### ISSUE TITLE
使用laravel属于多此一举的开发，建议该应用独立使用网易云音乐API

### ISSUE THREAD

**Issue by medz** [LaravelChen/vue-music#1]
网易云音乐API是可以直接返回的～没有必要从后端拿到数据后做二次封装，其次，应用会导致流量入口均在服务器。

你考虑下，如果用户多了，一半服务器承载不了这种流量的。其次，作为单页应用，明显已有API的情况下不再需要任何后端支持。

其次，作为前端应用～你也可以放到github pages中产生演示。

以上纯属建议。

**Comment by LaravelChen** [comment]
嗯嗯！本来做着玩的，感谢！

**Comment by medz** [comment]
@LaravelChen 做着玩也做的很不错了～ 作为独立SPA其实可以成为vue学习素材～

**Comment by LaravelChen** [comment]
嗯嗯谢谢！哈哈@medz
